pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [olafurpg]
      label:
        add: [dependency-update]
  - name: merge Scala Steward's PRs
    conditions:
      - base=master
      - author=scala-steward
      - status-success=build
    actions:
      merge:
        method: squash
